/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>
#include <sdkhooks>
#include <protobuf>

public Plugin:myinfo = 
{
	name = "Modyfikacja Rozgrzewki",
	author = "CSnajper",
	description = "Modyfikacja rozgrzewki",
	version = "1.0",
	url = "http://CSnajper.eu"
}

new g_iPlayer = -1;

public OnPluginStart()
{
	HookEvent("player_spawn", Event_PlayerSpawn, EventHookMode_Pre);
	g_iPlayer = FindSendPropOffs("CCSPlayer", "m_iAccount");
}

public Action:Event_PlayerSpawn(Handle:event, const String:name[], bool:dontBroadcast)
{
	new client = GetClientOfUserId(GetEventInt(event, "userid") );
	if(GameRules_GetProp("m_bWarmupPeriod") == 1)
		SetEntData(client, g_iPlayer, 0)
	return Plugin_Continue;
}