#if defined _cmodskills_included
 #endinput
#endif
#define _cmodskills_included

/**
 * ----------------------------------------
 *                   Skills
 * ----------------------------------------
 */

native Miny(client, ileKlasa, ileItem);
native OdpornoscNaMiny(client, klasa, item);
native KladzMine(client);

native Rakiety(client, ileKlasa, ileItem);
native OdpornoscNaRakiety(client, klasa, item)
native StworzRakiete(client);

native Skoki(client, ileKlasa, ileItem);

native OdnowienieMagazynka(client, klasa, item);
native UnlimitedClip(client, klasa, item);

native Wybuch(client, klasa, item);

native Teleport(client, klasa, item);

native Dynamit(client, klasa, item);
native OdpornoscNaDynamit(client, klasa, item);
native PolozDynamit(client);

native Apteczki(client, ileKlasa, ileItem);
native StworzApteczke(client);

native Respawn(client, szansaKlasa, szansaItem);

native Sanitarne(client, ileKlasa, ileItem);

native ZmienUbranie(client, klasa, item);

native Przygwozdzenie(client, klasa, item);

native Granat(client, klasa, item);

native Ultra(client, klasa, item);

native Vampire(client, klasa, item);

native AntyFlash(client, klasa, item);

native AntyHE(client, klasa, item);

native Cichobiegi(client, klasa, item);
